//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Second_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TablePremierLeague1
    {
        public int id { get; set; }
        public string Picture { get; set; }
        public string Name { get; set; }
        public string PreviousClub { get; set; }
        public string CurrentClub { get; set; }
        public Nullable<int> Age { get; set; }
        public string Position { get; set; }
        public string MarketValue { get; set; }
        public string Nationality { get; set; }
        public Nullable<int> Likes { get; set; }
        public Nullable<int> Dislikes { get; set; }
        public string Information { get; set; }
        public Nullable<int> InternationalMatches { get; set; }
        public string UserName { get; set; }
    }
}
